[tool.poetry]
name = "linkml-solr"
version = "0.1.0"
description = ""
authors = ["Chris Mungall <cjm@berkeleybop.org>"]

[tool.poetry.scripts]
lsolr = "linkml_solr.cli:main"

[tool.poetry.dependencies]
python = "^3.7.4"
linkml = "^1.1.15"
linkml-runtime = "^1.1.12"
pyparsing = "2.4"
SPARQLWrapper = "^1.8.5"
pysolr = "^3.9.0"
flatten-dict = "^0.4.2"
json-flattener = "^0.1.9"

[tool.poetry.dev-dependencies]
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
